spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tax_application?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id:
            client-secret:
            scope: openid+profile+email
            authorization-grant-type: authorization_code
          google:
            client-id:
            client-secret:
            scope: openid+profile+email
        provider:
          keycloak:
            issuer-uri: https://lemur-9.cloud-iam.com/auth/realms/shoppiq
          google:
            issuer-uri: https://accounts.google.com

server:
  port: 8082

keycloak:
  realm: shoppiq
  auth-server-url: https://lemur-9.cloud-iam.com/auth
  resource: shoppiqClient
  public-client: true
  bearer-only: true