kind: Application

spring:
  application:
    name: shoppiq
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  session:
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
             - openid
             - profile
             - email

jwt:
  secret: ${JWT_SECRET}
  expiration: 2592000000
  short-expiration: 1800000

app:
  security:
    secure-cookie: false

logging:
  level:
    com.crud.project.shoppiq: OFF

server:
  port: 8090