spring:
  application:
    name: shoppiq

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cnkart_schema
    username: root
    password: spring@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create

  session:
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always

server:
  port: 8090